version: "2.3"

services:
  postgresql:
    image: postgres:9.6.17-alpine
    hostname: postgresql
    restart: unless-stopped
    environment:
    - POSTGRES_MODE=primary
    - POSTGRES_USER=sqluser
    - POSTGRES_PASSWORD=sqlpassword
    - POSTGRES_ROOT_PASSWORD=sqlrootpassword
    - POSTGRES_PRIMARY_PORT=5432
    - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
    - "5432:5432"
  
  web:
    image: web
    restart: unless-stopped
    ports:
    - "5000:5000"
    build:
      context: .
      dockerfile: docker/web.dockerfile

  crawler:
    image: crawler
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/crawler.dockerfile
